package main

var tools = map[string]string{
	"Compass":              "罗盘",
	"Silk Spear":           "丝之矛",
	"Rosary Magnet":        "胸针磁石",
	"Sting Shard":          "蛰刺碎片",
	"Straight Pin":         "直针",
	"Thread Sphere":        "灵丝风暴",
	"Weighted Anklet":      "负重环带",
	"Flea Brew":            "跳蚤秘酿",
	"Poison Pouch":         "花芯嚢",
	"Mosscreep Tool 1":     "德鲁伊之眼",
	"White Ring":           "织光仪",
	"Bell Bind":            "护佑钟",
	"Fractured Mask":       "碎面甲",
	"Curve Claws":          "弧爪",
	"Curve Claws Upgraded": "曲镰",
	"Pimpilo":              "爆燃嚢",
	"Multibind":            "多重缚丝器",
	"Lava Charm":           "熔岩钟",
	"Flintstone":           "燧石板",
	"Dazzle Bind":          "爪镜",
	"Revenge Crystal":      "记忆晶石",
	"Dead Mans Purse":      "亡虫嚢",
	"Shell Satchel":        "壳囊",
	"Wallcling":            "登极握爪",
	"Silk Charge":          "丝刃镖",
	"Lifeblood Syringe":    "生质液瓶",
	"Mosscreep Tool 2":     "德鲁伊双瞳",
	"Thief Charm":          "窃者印记",
	"Magnetite Dice":       "磁石骰",
	"Thief Claw":           "撬赃钩",
	"Spool Extender":       "储丝延展器",
	"Cogwork Flier":        "齿轮蜂",
	"Quickbind":            "注丝套针",
	"Tack":                 "钉刺",
	"Bone Necklace":        "碎壳坠",
	"Cogwork Saw":          "机轮刃",
	"Conch Drill":          "螺切刃",
	"Zap Imbuement":        "伏特丝",
	"Sprintmaster":         "丝速脚环",
	"Lightning Rod":        "电枢球",
	"Tri Pin":              "三重镖",
	"Screw Attack":         "掘洞钻",
	"Wisp Lantern":         "灵火提灯",
	"Maggot Charm":         "净界花环",
	"Longneedle":           "长爪",
	"Silk Bomb":            "符文之怒",
	"Barbed Wire":          "棘刺手环",
	"Parry":                "十字绣",
	"Quick Sling":          "速射索",
	"Brolly Spike":         "锯齿环",
	"Musician Charm":       "蛛丝弦",
	"Rosary Cannon":        "念珠炮",
	"Reserve Bind":         "储备缚丝",
	"Scuttlebrace":         "迅捷脊锁",
	"Shakra Ring":          "投掷环",
	"Harpoon":              "长针",
	"WebShot Weaver":       "丝弹（雪山）",
	"WebShot Forge":        "丝弹（熔炉之女）",
	"WebShot Architect":    "丝弹（建筑师）",
	"Flea Charm":           "蚤母卵",
	"Pinstress Tool":       "针徽",
	"Dazzle Bind Upgraded": "双生爪镜",
	"Silk Boss Needle":     "苍白之爪",
}

var upgradedTools = []string{"Mosscreep Tool 2", "Dazzle Bind Upgraded", "WebShot Weaver", "WebShot Forge", "WebShot Architect", "Curve Claws Upgraded"}

var toolEquips = map[string]string{
	"Reaper":     "收割者纹章",
	"Wanderer":   "漫游者纹章",
	"Warrior":    "野兽纹章",
	"Toolmaster": "建筑师纹章",
	"Witch":      "巫妪纹章",
	"Spell":      "萨满纹章",
}
