// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeGame(arg1) {
  return window['go']['main']['App']['ChangeGame'](arg1);
}

export function ChooseDataFile() {
  return window['go']['main']['App']['ChooseDataFile']();
}

export function ModifyScript() {
  return window['go']['main']['App']['ModifyScript']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function RefreshUserData() {
  return window['go']['main']['App']['RefreshUserData']();
}

export function SaveBuf() {
  return window['go']['main']['App']['SaveBuf']();
}

export function SaveScreenshot(arg1) {
  return window['go']['main']['App']['SaveScreenshot'](arg1);
}

export function SelectUserData(arg1) {
  return window['go']['main']['App']['SelectUserData'](arg1);
}

export function ShowDataFolder() {
  return window['go']['main']['App']['ShowDataFolder']();
}
